
model_path: ./VE-State
model_archive: ~/vision-eval/VisionEval-Archive
model_source: E:/Projects/Clients/odot/ODOT_VEState/Github/built/mm_model/4.1.0/runtime/models/VE-State
model_hist_datastore: E:/Projects/Clients/odot/ODOT_VEState/Github/sources/models/VE-State-EMAT/BaseDatastore
model_temp_folder: E:/Projects/Clients/odot/ODOT_VEState/Github/sources/models/VE-State-EMAT/Temporary

rel_output_path: ./output
r_library_path: E:/Projects/Clients/odot/ODOT_VEState/Github/built/mm_model/4.1.0/ve-lib
r_runtime_path: E:/Projects/Clients/odot/ODOT_VEState/Github/built/mm_model/4.1.0/runtime
r_executable: E:/Projects/Clients/odot/ODOT_VEState/R_4_1_0/App/R-Portable/bin
